name: 'Deploy to SFTP'
description: 'Deploy to an SFTP server with no downtime'

inputs:
  keep:
    description: "The list of folder and files that should not be changed on the remote, in JSON list format"
    type: string
    default: '[]'
    required: false
  host:
    description: "The server host or ip"
    type: string
    required: true
  port:
    description: "The server port"
    default: 22
    required: false
  local_path:
    description: "The local path to deploy"
    type: string
    default: './'
    required: false
  remote_path:
    description: "The remote path in which to deploy"
    type: string
    required: true
  user:
    description: "The SSH user to use"
    type: string
    required: true
  private_key:
    description: "The SSH private key used for authentication"
    type: string
    required: true
  post_deploy_commands:
    description: "A command or commands tu run after the files were copied to the server but before the version is promoted to current."
    type: string
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Get formatted datetime
      id: date
      shell: bash
      run: echo "value=$(date +%Y-%m-%d_%H-%M)" >> $GITHUB_OUTPUT

    - name: TAR Files
      shell: bash
      run: |
        tar -cvzf /tmp/build.tar.gz '${{ inputs.local_path }}'
        ls -la /tmp

    - name: Setup remote filesystem structure
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ inputs.host }}
        port: ${{ inputs.port }}
        username: ${{ inputs.user }}
        key: ${{ inputs.private_key }}
        script: |
          cd ${{ inputs.remote_path }}
          if [ ! -d "versions" ]; then
            mkdir "versions"
          fi
          if [ ! -d "permanent" ]; then
            mkdir "permanent"
          fi
          mkdir "versions/${{ steps.date.outputs.value }}"

    - name: Deploy to server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.5
      with:
        server: ${{ inputs.host }}
        port: ${{ inputs.port }}
        username: ${{ inputs.user }}
        ssh_private_key: ${{ inputs.private_key }}
        local_path: '/tmp/build.tar.gz'
        remote_path: '${{ inputs.remote_path }}/versions/${{ steps.date.outputs.value }}'


    - name: Finish deployment
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ inputs.host }}
        port: ${{ inputs.port }}
        username: ${{ inputs.user }}
        key: ${{ inputs.private_key }}
        script: |
          version_folder="${{ inputs.remote_path }}/versions/${{ steps.date.outputs.value }}"
          cd $version_folder
          
          tar -xvzf build.tar.gz
          
          cd ${{ inputs.remote_path }}

          # Link permanent directories
          for name in '${{ join(fromJSON(inputs.keep), ''' ''') }}'; do
            permanent="permanent/$name"
            versionned="$version_folder/$name"
            if [ ! -e $permanent ]; then
              if [ ! -e $versionned ]; then
                echo "WARNING: $permanent: file not found"
              else
                echo "WARNING: $permanent: file not found, will copy the existing version from the version"
                cp $versionned $permanent
                rm -rf $versionned
              fi
            elif [ -e $versionned ]; then
                echo "WARNING: $permanent: this file exist in the versionned files, it will be deleted."
                rm -rf $versionned
            fi
            ln -s "${{ inputs.remote_path }}/permanent/$name" "${{ inputs.remote_path }}/versions/${{ steps.date.outputs.value }}/$name"
          done
          
          cd "${{ inputs.remote_path }}/versions/${{ steps.date.outputs.value }}"
          ${{ inputs.post_deploy_commands }}
          
          cd ${{ inputs.remote_path }}

          # Update current link
          ln -snf "${{ inputs.remote_path }}/versions/${{ steps.date.outputs.value }}/" "${{ inputs.remote_path }}/current"

          # Remove older version beyond the last 5
          cd ${{ inputs.remote_path }}/versions
          ls -1tr | head -n -5 | xargs -L1 -I% rm -r '%' 
